### ISSUE TITLE
Several problems when using toolScript

### ISSUE THREAD

**Issue by askask** [eilslabs/BatchEuphoria#12]
When using toolString, 
- calling `PbsCommand.toString` results in an NPE
- calling `BEJob.toString` results in an NPE
- calling `PbsJobManager.createCommand` results in an NPE
- the PBS submission command is not created correctly (should pipe the `toolScript` into `qsub`, instead of using it as an argugment)

**Comment by dankwart-de** [comment]
This is not yet working for PBS. In Roddy I don't use it (or at least not until now). Do you need it for OTP?

**Comment by askask** [comment]
Yes, that would make integration in OTP easier. It shouldn't be difficult to support it, see my pull request

**Comment by dankwart-de** [comment]
Can this be closed?
