### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by dankwart-de** [eilslabs/BatchEuphoria#17]
```
de.dkfz.roddy.execution.cluster.pbs.PBSCommandParserTest > testConstructAndParseSimpleJob FAILED
    org.codehaus.groovy.runtime.powerassert.PowerAssertionError at PBSCommandParserTest.groovy:49
```

Don't know why. The test works fine on my local machine and does not use the file or cluster system.

**Comment by fkaercher** [comment]
I receive the same error but only when I check out tag 0.0.01

**Comment by fkaercher** [comment]
I think the problem was fixed here: https://github.com/eilslabs/BatchEuphoria/commit/b8c32c756576951f68942327cd7fc23e70b7651b
