### ISSUE TITLE
Method to query job state for all jobs

### ISSUE THREAD

**Issue by askask** [eilslabs/BatchEuphoria#22]
It would be great if BE had a method to query the job states for all jobs of a user.
I noticed that it already updates the all job states internally, and for OTP it would be useful to expose that information.

**Comment by dankwart-de** [comment]
If I understand you correctly, what you want is qstat -u right?
This is already implemented:
Look into JobManagerCreationParameters, there you'll find two fields userIdForJobQueries and trackUserJobsOnly

**Comment by askask** [comment]
But there are currently no methods to get the complete results of `qstat -u`; `queryJobStatus` requires that you pass a list of BEJobs.
See the methods added in the queryJobStatus branch.
