### ISSUE TITLE
Implement Job Manager Builder code to support maps and maybe introduce specialized classes

### ISSUE THREAD

**Issue by dankwart-de** [eilslabs/BatchEuphoria#25]

**Comment by vinjana** [comment]
Something like `JobManager(..., Map<String,String> additionalParameters)`.
Strict handling of wrong parameter (map keys) to catch typos.

If this is only about authentication only, better explicitly code this as AuthCredetials classes (Username + PWD, Username + Key, Username [e.g. if SSHAgent], Null [if ExecutionService is already connected).
