### ISSUE TITLE
User should know if PBSJobManager.updateJobStatus failed

### ISSUE THREAD

**Issue by askask** [eilslabs/BatchEuphoria#26]
When I call one of the queryJobStatus* methods in PBSJobManager, and get back an empty map, I don't know whether no jobs are running anymore, or updateJobStatus/qstat failed.

**Comment by dankwart-de** [comment]
see PR27 https://github.com/eilslabs/BatchEuphoria/pull/27
Let's discuss if this is feasible

**Comment by vinjana** [comment]
The classical way to handle such situation in Java is via exceptions. So better throw an exception with a descriptive message and use appropriate exception classes expressing "qstat failed" and "job not found"!

**Comment by vinjana** [comment]
* When is the result empty?
* Is there a cache for the job status table?
* Do we need caching with LSF?
* Is the cache ever emptied? How (expiration time? round-robin?)

**Comment by vinjana** [comment]
Covered by solution #93, to throw an excpetion upon command error.
