### ISSUE TITLE
Handle location of log files for different systems

### ISSUE THREAD

**Issue by askask** [eilslabs/BatchEuphoria#46]
In **PBS**, if you pass
 - nothing: a file a file [jobname].[o|e][jobid] in your home directory
 - -o/-e with an existing directory, it will write a file [jobname].[o|e][jobid] in that directory
 - -o/-e with a filename in an existing directory, it will use that filename, if the parent directory doesn't exist, nothing is written

You need to pass -joe to combine stdout and stderr
To write nothing, the you need to use the -k option 
Variable "$PBS_JOBID" in the path will be replaced by the job id

In **LFS**, if you pass
 - nothing: nothing is written
 - -oo/-eo with an existing directory, it will write a file [jobid].out in that directory
 - -oo/-eo with a filename in an existing directory, it will use that filename, if the parent directory doesn't exist, nothing is written

Stderr is written to the same file as stdout if you don't pass -eo/-e; it seems that also happens if you pass the same directory to both -oo and -eo.
%J in the path will be replaced by the job id, and %I by the array index

**BE should make sure that if you use the same options, the same files are written with all systems.**

**Comment by vinjana** [comment]
Did you try that out for LSF and output to a single file? It seems not to work!
```
echo "echo stderr > /dev/stderr; echo stdout > /dev/stdout" | bsub -o test1 -e test1
echo "echo stderr > /dev/stderr; echo stdout > /dev/stdout" | bsub -o test2
echo "echo stderr > /dev/stderr; echo stdout > /dev/stdout" | bsub -o test3.out -e test3.err
```
The only command that produces "stderr" in some file is the third one!

**Comment by fkaercher** [comment]
@vinjana When using `> /dev/stdout` and `> /dev/stderr` it seems to overwrite the previous output.
I tried it with the following commands and it worked:
```
# writes both to test1.out
echo 'echo stderr 1>&2; echo stdout' | bsub -o test1.out -e test1.out

# writes both to test2.out
echo 'echo stderr 1>&2; echo stdout' | bsub -o test2.out

# writes to test3.out and test3.err respectively
echo 'echo stderr 1>&2; echo stdout' | bsub -o test3.out -e test3.err
```
