### ISSUE TITLE
BEJob.getShortID() doesn't return short ID

### ISSUE THREAD

**Issue by askask** [eilslabs/BatchEuphoria#69]
It just returns `BEJob.id`.
This causes problems in OTP because it expecpts the short ID (number only).

**Comment by vinjana** [comment]
There may be a general inconsistency in how job IDs are handled. E.g. in de.dkfz.roddy.execution.jobs.cluster.pbs.PBSJobManager#readQstatOutput long PBS job ids are not parsed fully, but only short IDs are parsed.

**Comment by vinjana** [comment]
Always use and parse the full ID. The shortID should however be used submitting dependencies via the command line (where a long ID with many jobs can be problematic).

**Comment by vinjana** [comment]
Concept for handling short and long IDs in PBS (which don't exist in LSF).

* How to map between the two, if the user puts one or the other in a BEJobID object?
* Which one is the canonical representation (e.g. with BEJobID.toString())?
