### ISSUE TITLE
Don't depend on SNAPSHOT versions

### ISSUE THREAD

**Issue by askask** [eilslabs/BatchEuphoria#92]
When using SNAPSHOT versions, the dependency is downloaded every time. this also happens for transitive dependencies, such as when compiling OTP.

**Comment by vinjana** [comment]
What should be the alternative then during development? In the release version the commit/tag will be fixed.

**Comment by vinjana** [comment]
This is not a bug but intended behavior ;-)

**Comment by askask** [comment]
> In the release version the commit/tag will be fixed.
I didn't know that, that's ok for me
